version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  mac:
    macos:
      xcode: 10.1.0
workflows:
  build:
    jobs:
      - cypress/run:
          name: Linux test

wworkflows:
    
      jobs:
        - cypress/run:
            parallelism: 5 
            parallel: true 
            record: false 
            component: false 
