# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.4.0
  aws-cli: circleci/aws-cli@0.1.16
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
workflows:
  say-hello-workflow:
    jobs:
      - cypress/run
      
